---
# Ansible playbook for installing applications on Centos and Ubuntu
# Author: Oliver Gillum-Webb

- name: Install CentOS/RHEL software
  yum: pkg={{item}} state=latest
  with_items:
    - libselinux-python
    - ntp
    - net-tools
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Debian/Ubuntu Software
  apt: pkg={{ item }} update_cache=yes state=present
  with_items:
    - python-pycurl
    - python-apt
    - ntpd
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
